# docker-compose.yml

# Specifies the version of the Docker Compose file format.
version: '3.8'

# Defines the services (containers) that make up your application.
services:
  # The Python backend service.
  backend:
    # Tells Docker Compose to build the image from the 'backend' directory.
    build: ./backend
    # Names the container for easier identification.
    container_name: python_backend
    # We don't need to map ports to the host machine because Nginx will handle communication.
    # The Flask app will be available on port 5000 inside the Docker network.
    expose:
      - 5000

  # The Nginx web server and reverse proxy.
  nginx:
    # Use a lightweight, official Nginx image from Docker Hub.
    image: nginx:alpine
    container_name: nginx_proxy
    # Maps port 8080 on your local machine to port 80 inside the Nginx container.
    # This is how you will access the application from your browser.
    ports:
      - "8080:80"
    # Mounts local files/directories into the container.
    volumes:
      # Mounts the frontend code into the default Nginx web root directory.
      - ./frontend:/usr/share/nginx/html
      # Mounts our custom Nginx configuration file.
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    # Ensures that the 'backend' service is started before this service.
    depends_on:
      - backend