services:
  backend:
    build: ./backend
    container_name: python_backend
    expose:
      - 5000
    volumes:
      - ./backend:/app

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend